### ISSUE TITLE
Cannot connect to non-encrypted server via DDNS

### ISSUE THREAD

**Issue by GodTamIt** [BlueBubblesApp/web#2]
I have a DDNS setup that's working for both the desktop and Android apps but cannot connect via the web.

Feel free to follow up here -- happy to put up any debug information that's necessary.

**Comment by tneotia** [comment]
Hi there, sorry for the late response, we don't check this repository often - it's just the deployment for GitHub Pages. Our actual repo holding the code to the webapp is the bluebubbles_app repo.

As for this issue, web requires use of https so any non-https (e.g. http or tcp) setups do not work. Nothing we can do on our side unfortunately, browsers will simply block our requests to connect to non-https domains.

**Comment by GodTamIt** [comment]
Does the web-server support https?

**Comment by GodTamIt** [comment]
For posterity, I got a self-hosted DDNS with https working with an nginx server + ddclient + Certbot (LetsEncrypt).

For nginx config: https://gist.github.com/GodTamIt/d8a86bc96647630250c2f6107fd17b9a
